/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mhash_MHash384 */

#ifndef _Included_mhash_MHash384
#define _Included_mhash_MHash384
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class mhash_MHash384_Internals */

#ifndef _Included_mhash_MHash384_Internals
#define _Included_mhash_MHash384_Internals
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mhash_MHash384_Internals
 * Method:    createInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_mhash_MHash384_00024Internals_createInstance
  (JNIEnv *, jclass);

/*
 * Class:     mhash_MHash384_Internals
 * Method:    update
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_mhash_MHash384_00024Internals_update
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     mhash_MHash384_Internals
 * Method:    finalize
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_mhash_MHash384_00024Internals_finalize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mhash_MHash384_Internals
 * Method:    destroyInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mhash_MHash384_00024Internals_destroyInstance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mhash_MHash384_Internals
 * Method:    getVersion
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_mhash_MHash384_00024Internals_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
